<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('countries')->truncate();

        DB::insert("insert into countries (id, country, iso2, iso3, currency, currency_symbol, created_at, updated_at)
values  (1, 'Afghanistan', null, null, null, null, null, null),
        (2, 'Albania', null, null, null, null, null, null),
        (3, 'Algeria', null, null, null, null, null, null),
        (4, 'American Samoa', null, null, null, null, null, null),
        (5, 'Andorra', null, null, null, null, null, null),
        (6, 'Angola', null, null, null, null, null, null),
        (7, 'Anguilla', null, null, null, null, null, null),
        (8, 'Antarctica', null, null, null, null, null, null),
        (9, 'Antigua And Barbuda', null, null, null, null, null, null),
        (10, 'Argentina', null, null, null, null, null, null),
        (11, 'Armenia', null, null, null, null, null, null),
        (12, 'Aruba', null, null, null, null, null, null),
        (13, 'Australia', null, null, null, null, null, null),
        (14, 'Austria', null, null, null, null, null, null),
        (15, 'Azerbaijan', null, null, null, null, null, null),
        (16, 'Bahamas The', null, null, null, null, null, null),
        (17, 'Bahrain', null, null, null, null, null, null),
        (18, 'Bangladesh', null, null, null, null, null, null),
        (19, 'Barbados', null, null, null, null, null, null),
        (20, 'Belarus', null, null, null, null, null, null),
        (21, 'Belgium', null, null, null, null, null, null),
        (22, 'Belize', null, null, null, null, null, null),
        (23, 'Benin', null, null, null, null, null, null),
        (24, 'Bermuda', null, null, null, null, null, null),
        (25, 'Bhutan', null, null, null, null, null, null),
        (26, 'Bolivia', null, null, null, null, null, null),
        (27, 'Bosnia and Herzegovina', null, null, null, null, null, null),
        (28, 'Botswana', null, null, null, null, null, null),
        (29, 'Bouvet Island', null, null, null, null, null, null),
        (30, 'Brazil', null, null, null, null, null, null),
        (31, 'British Indian Ocean Territory', null, null, null, null, null, null),
        (32, 'Brunei', null, null, null, null, null, null),
        (33, 'Bulgaria', null, null, null, null, null, null),
        (34, 'Burkina Faso', null, null, null, null, null, null),
        (35, 'Burundi', null, null, null, null, null, null),
        (36, 'Cambodia', null, null, null, null, null, null),
        (37, 'Cameroon', null, null, null, null, null, null),
        (38, 'Canada', null, null, null, null, null, null),
        (39, 'Cape Verde', null, null, null, null, null, null),
        (40, 'Cayman Islands', null, null, null, null, null, null),
        (41, 'Central African Republic', null, null, null, null, null, null),
        (42, 'Chad', null, null, null, null, null, null),
        (43, 'Chile', null, null, null, null, null, null),
        (44, 'China', null, null, null, null, null, null),
        (45, 'Christmas Island', null, null, null, null, null, null),
        (46, 'Cocos (Keeling) Islands', null, null, null, null, null, null),
        (47, 'Colombia', null, null, null, null, null, null),
        (48, 'Comoros', null, null, null, null, null, null),
        (49, 'Republic Of The Congo', null, null, null, null, null, null),
        (50, 'Democratic Republic Of The Congo', null, null, null, null, null, null),
        (51, 'Cook Islands', null, null, null, null, null, null),
        (52, 'Costa Rica', null, null, null, null, null, null),
        (53, 'Cote DIvoire (Ivory Coast)', null, null, null, null, null, null),
        (54, 'Croatia (Hrvatska)', null, null, null, null, null, null),
        (55, 'Cuba', null, null, null, null, null, null),
        (56, 'Cyprus', null, null, null, null, null, null),
        (57, 'Czech Republic', null, null, null, null, null, null),
        (58, 'Denmark', null, null, null, null, null, null),
        (59, 'Djibouti', null, null, null, null, null, null),
        (60, 'Dominica', null, null, null, null, null, null),
        (61, 'Dominican Republic', null, null, null, null, null, null),
        (62, 'East Timor', null, null, null, null, null, null),
        (63, 'Ecuador', null, null, null, null, null, null),
        (64, 'Egypt', null, null, null, null, null, null),
        (65, 'El Salvador', null, null, null, null, null, null),
        (66, 'Equatorial Guinea', null, null, null, null, null, null),
        (67, 'Eritrea', null, null, null, null, null, null),
        (68, 'Estonia', null, null, null, null, null, null),
        (69, 'Ethiopia', null, null, null, null, null, null),
        (70, 'External Territories of Australia', null, null, null, null, null, null),
        (71, 'Falkland Islands', null, null, null, null, null, null),
        (72, 'Faroe Islands', null, null, null, null, null, null),
        (73, 'Fiji Islands', null, null, null, null, null, null),
        (74, 'Finland', null, null, null, null, null, null),
        (75, 'France', null, null, null, null, null, null),
        (76, 'French Guiana', null, null, null, null, null, null),
        (77, 'French Polynesia', null, null, null, null, null, null),
        (78, 'French Southern Territories', null, null, null, null, null, null),
        (79, 'Gabon', null, null, null, null, null, null),
        (80, 'Gambia The', null, null, null, null, null, null),
        (81, 'Georgia', null, null, null, null, null, null),
        (82, 'Germany', null, null, null, null, null, null),
        (83, 'Ghana', null, null, null, null, null, null),
        (84, 'Gibraltar', null, null, null, null, null, null),
        (85, 'Greece', null, null, null, null, null, null),
        (86, 'Greenland', null, null, null, null, null, null),
        (87, 'Grenada', null, null, null, null, null, null),
        (88, 'Guadeloupe', null, null, null, null, null, null),
        (89, 'Guam', null, null, null, null, null, null),
        (90, 'Guatemala', null, null, null, null, null, null),
        (91, 'Guernsey and Alderney', null, null, null, null, null, null),
        (92, 'Guinea', null, null, null, null, null, null),
        (93, 'Guinea-Bissau', null, null, null, null, null, null),
        (94, 'Guyana', null, null, null, null, null, null),
        (95, 'Haiti', null, null, null, null, null, null),
        (96, 'Heard and McDonald Islands', null, null, null, null, null, null),
        (97, 'Honduras', null, null, null, null, null, null),
        (98, 'Hong Kong S.A.R.', null, null, null, null, null, null),
        (99, 'Hungary', null, null, null, null, null, null),
        (100, 'Iceland', null, null, null, null, null, null),
        (101, 'India', null, null, null, null, null, null),
        (102, 'Indonesia', null, null, null, null, null, null),
        (103, 'Iran', null, null, null, null, null, null),
        (104, 'Iraq', null, null, null, null, null, null),
        (105, 'Ireland', null, null, null, null, null, null),
        (107, 'Italy', null, null, null, null, null, null),
        (108, 'Jamaica', null, null, null, null, null, null),
        (109, 'Japan', null, null, null, null, null, null),
        (110, 'Jersey', null, null, null, null, null, null),
        (111, 'Jordan', null, null, null, null, null, null),
        (112, 'Kazakhstan', null, null, null, null, null, null),
        (113, 'Kenya', null, null, null, null, null, null),
        (114, 'Kiribati', null, null, null, null, null, null),
        (115, 'Korea North', null, null, null, null, null, null),
        (116, 'Korea South', null, null, null, null, null, null),
        (117, 'Kuwait', null, null, null, null, null, null),
        (118, 'Kyrgyzstan', null, null, null, null, null, null),
        (119, 'Laos', null, null, null, null, null, null),
        (120, 'Latvia', null, null, null, null, null, null),
        (121, 'Lebanon', null, null, null, null, null, null),
        (122, 'Lesotho', null, null, null, null, null, null),
        (123, 'Liberia', null, null, null, null, null, null),
        (124, 'Libya', null, null, null, null, null, null),
        (125, 'Liechtenstein', null, null, null, null, null, null),
        (126, 'Lithuania', null, null, null, null, null, null),
        (127, 'Luxembourg', null, null, null, null, null, null),
        (128, 'Macau S.A.R.', null, null, null, null, null, null),
        (129, 'Macedonia', null, null, null, null, null, null),
        (130, 'Madagascar', null, null, null, null, null, null),
        (131, 'Malawi', null, null, null, null, null, null),
        (132, 'Malaysia', null, null, null, null, null, null),
        (133, 'Maldives', null, null, null, null, null, null),
        (134, 'Mali', null, null, null, null, null, null),
        (135, 'Malta', null, null, null, null, null, null),
        (136, 'Man (Isle of)', null, null, null, null, null, null),
        (137, 'Marshall Islands', null, null, null, null, null, null),
        (138, 'Martinique', null, null, null, null, null, null),
        (139, 'Mauritania', null, null, null, null, null, null),
        (140, 'Mauritius', null, null, null, null, null, null),
        (141, 'Mayotte', null, null, null, null, null, null),
        (142, 'Mexico', null, null, null, null, null, null),
        (143, 'Micronesia', null, null, null, null, null, null),
        (144, 'Moldova', null, null, null, null, null, null),
        (145, 'Monaco', null, null, null, null, null, null),
        (146, 'Mongolia', null, null, null, null, null, null),
        (147, 'Montserrat', null, null, null, null, null, null),
        (148, 'Morocco', null, null, null, null, null, null),
        (149, 'Mozambique', null, null, null, null, null, null),
        (150, 'Myanmar', null, null, null, null, null, null),
        (151, 'Namibia', null, null, null, null, null, null),
        (152, 'Nauru', null, null, null, null, null, null),
        (153, 'Nepal', null, null, null, null, null, null),
        (154, 'Netherlands Antilles', null, null, null, null, null, null),
        (155, 'Netherlands The', null, null, null, null, null, null),
        (156, 'New Caledonia', null, null, null, null, null, null),
        (157, 'New Zealand', null, null, null, null, null, null),
        (158, 'Nicaragua', null, null, null, null, null, null),
        (159, 'Niger', null, null, null, null, null, null),
        (160, 'Nigeria', null, null, null, null, null, null),
        (161, 'Niue', null, null, null, null, null, null),
        (162, 'Norfolk Island', null, null, null, null, null, null),
        (163, 'Northern Mariana Islands', null, null, null, null, null, null),
        (164, 'Norway', null, null, null, null, null, null),
        (165, 'Oman', null, null, null, null, null, null),
        (166, 'Pakistan', null, null, null, null, null, null),
        (167, 'Palau', null, null, null, null, null, null),
        (168, 'Palestinian Territory Occupied', null, null, null, null, null, null),
        (169, 'Panama', null, null, null, null, null, null),
        (170, 'Papua new Guinea', null, null, null, null, null, null),
        (171, 'Paraguay', null, null, null, null, null, null),
        (172, 'Peru', null, null, null, null, null, null),
        (173, 'Philippines', null, null, null, null, null, null),
        (174, 'Pitcairn Island', null, null, null, null, null, null),
        (175, 'Poland', null, null, null, null, null, null),
        (176, 'Portugal', null, null, null, null, null, null),
        (177, 'Puerto Rico', null, null, null, null, null, null),
        (178, 'Qatar', null, null, null, null, null, null),
        (179, 'Reunion', null, null, null, null, null, null),
        (180, 'Romania', null, null, null, null, null, null),
        (181, 'Russia', null, null, null, null, null, null),
        (182, 'Rwanda', null, null, null, null, null, null),
        (183, 'Saint Helena', null, null, null, null, null, null),
        (184, 'Saint Kitts And Nevis', null, null, null, null, null, null),
        (185, 'Saint Lucia', null, null, null, null, null, null),
        (186, 'Saint Pierre and Miquelon', null, null, null, null, null, null),
        (187, 'Saint Vincent And The Grenadines', null, null, null, null, null, null),
        (188, 'Samoa', null, null, null, null, null, null),
        (189, 'San Marino', null, null, null, null, null, null),
        (190, 'Sao Tome and Principe', null, null, null, null, null, null),
        (191, 'Saudi Arabia', null, null, null, null, null, null),
        (192, 'Senegal', null, null, null, null, null, null),
        (193, 'Serbia', null, null, null, null, null, null),
        (194, 'Seychelles', null, null, null, null, null, null),
        (195, 'Sierra Leone', null, null, null, null, null, null),
        (196, 'Singapore', null, null, null, null, null, null),
        (197, 'Slovakia', null, null, null, null, null, null),
        (198, 'Slovenia', null, null, null, null, null, null),
        (199, 'Smaller Territories of the UK', null, null, null, null, null, null),
        (200, 'Solomon Islands', null, null, null, null, null, null),
        (201, 'Somalia', null, null, null, null, null, null),
        (202, 'South Africa', null, null, null, null, null, null),
        (203, 'South Georgia', null, null, null, null, null, null),
        (204, 'South Sudan', null, null, null, null, null, null),
        (205, 'Spain', null, null, null, null, null, null),
        (206, 'Sri Lanka', null, null, null, null, null, null),
        (207, 'Sudan', null, null, null, null, null, null),
        (208, 'Suriname', null, null, null, null, null, null),
        (209, 'Svalbard And Jan Mayen Islands', null, null, null, null, null, null),
        (210, 'Swaziland', null, null, null, null, null, null),
        (211, 'Sweden', null, null, null, null, null, null),
        (212, 'Switzerland', null, null, null, null, null, null),
        (213, 'Syria', null, null, null, null, null, null),
        (214, 'Taiwan', null, null, null, null, null, null),
        (215, 'Tajikistan', null, null, null, null, null, null),
        (216, 'Tanzania', null, null, null, null, null, null),
        (217, 'Thailand', null, null, null, null, null, null),
        (218, 'Togo', null, null, null, null, null, null),
        (219, 'Tokelau', null, null, null, null, null, null),
        (220, 'Tonga', null, null, null, null, null, null),
        (221, 'Trinidad And Tobago', null, null, null, null, null, null),
        (222, 'Tunisia', null, null, null, null, null, null),
        (223, 'Turkey', null, null, null, null, null, null),
        (224, 'Turkmenistan', null, null, null, null, null, null),
        (225, 'Turks And Caicos Islands', null, null, null, null, null, null),
        (226, 'Tuvalu', null, null, null, null, null, null),
        (227, 'Uganda', null, null, null, null, null, null),
        (228, 'Ukraine', null, null, null, null, null, null),
        (229, 'United Arab Emirates', null, null, null, null, null, null),
        (230, 'United Kingdom', null, null, null, null, null, null),
        (231, 'United States', null, null, null, null, null, null),
        (232, 'United States Minor Outlying Islands', null, null, null, null, null, null),
        (233, 'Uruguay', null, null, null, null, null, null),
        (234, 'Uzbekistan', null, null, null, null, null, null),
        (235, 'Vanuatu', null, null, null, null, null, null),
        (236, 'Vatican City State (Holy See)', null, null, null, null, null, null),
        (237, 'Venezuela', null, null, null, null, null, null),
        (238, 'Vietnam', null, null, null, null, null, null),
        (239, 'Virgin Islands (British)', null, null, null, null, null, null),
        (240, 'Virgin Islands (US)', null, null, null, null, null, null),
        (241, 'Wallis And Futuna Islands', null, null, null, null, null, null),
        (242, 'Western Sahara', null, null, null, null, null, null),
        (243, 'Yemen', null, null, null, null, null, null),
        (244, 'Yugoslavia', null, null, null, null, null, null),
        (245, 'Zambia', null, null, null, null, null, null),
        (246, 'Zimbabwe', null, null, null, null, null, null)");
    }
}
