<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('countries')->truncate();

        DB::insert("insert into countries (id, country, country_ar, iso2, iso3, currency, currency_symbol, created_at, updated_at)
values
(191, 'Afghanistan', 'أفغانستان', null, null, null, null, null, null),
(1, 'Saudi Arabia', 'المملكة العربية السعودية', null, null, null, null, null, null),
(2, 'Albania', 'ألبانيا', null, null, null, null, null, null),
(3, 'Algeria', 'الجزائر', null, null, null, null, null, null),
(4, 'American Samoa', 'ساموا الأمريكية', null, null, null, null, null, null),
(5, 'Andorra', 'أندورا', null, null, null, null, null, null),
(6, 'Angola', 'أنجولا', null, null, null, null, null, null),
(7, 'Anguilla', 'أنغويلا', null, null, null, null, null, null),
(8, 'Antarctica', 'أنتاركتيكا', null, null, null, null, null, null),
(9, 'Antigua And Barbuda', 'أنتيغوا وبربودا', null, null, null, null, null, null),
(10, 'Argentina', 'الأرجنتين', null, null, null, null, null, null),
(11, 'Armenia', 'أرمينيا', null, null, null, null, null, null),
(12, 'Aruba', 'أروبا', null, null, null, null, null, null),
(13, 'Australia', 'أستراليا', null, null, null, null, null, null),
(14, 'Austria', 'النمسا', null, null, null, null, null, null),
(15, 'Azerbaijan', 'أذربيجان', null, null, null, null, null, null),
(16, 'Bahamas The', 'الباهاما', null, null, null, null, null, null),
(17, 'Bahrain', 'البحرين', null, null, null, null, null, null),
(18, 'Bangladesh', 'بنغلاديش', null, null, null, null, null, null),
(19, 'Barbados', 'باربادوس', null, null, null, null, null, null),
(20, 'Belarus', 'بيلاروس', null, null, null, null, null, null),
(21, 'Belgium', 'بلجيكا', null, null, null, null, null, null),
(22, 'Belize', 'بليز', null, null, null, null, null, null),
(23, 'Benin', 'بنين', null, null, null, null, null, null),
(24, 'Bermuda', 'برمودا', null, null, null, null, null, null),
(25, 'Bhutan', 'بوتان', null, null, null, null, null, null),
(26, 'Bolivia', 'بوليفيا', null, null, null, null, null, null),
(27, 'Bosnia and Herzegovina', 'البوسنة والهرسك', null, null, null, null, null, null),
(28, 'Botswana', 'بوتسوانا', null, null, null, null, null, null),
(29, 'Bouvet Island', 'جزيرة بوفيه', null, null, null, null, null, null),
(30, 'Brazil', 'البرازيل', null, null, null, null, null, null),
(31, 'British Indian Ocean Territory', 'إقليم المحيط الهندي البريطاني', null, null, null, null, null, null),
(32, 'Brunei', 'بروناي', null, null, null, null, null, null),
(33, 'Bulgaria', 'بلغاريا', null, null, null, null, null, null),
(34, 'Burkina Faso', 'بوركينا فاسو', null, null, null, null, null, null),
(35, 'Burundi', 'بوروندي', null, null, null, null, null, null),
(36, 'Cambodia', 'كمبوديا', null, null, null, null, null, null),
(37, 'Cameroon', 'الكاميرون', null, null, null, null, null, null),
(38, 'Canada', 'كندا', null, null, null, null, null, null),
(39, 'Cape Verde', 'الرأس الأخضر', null, null, null, null, null, null),
(40, 'Cayman Islands', 'جزر كايمان', null, null, null, null, null, null),
(41, 'Central African Republic', 'جمهورية أفريقيا الوسطى', null, null, null, null, null, null),
(42, 'Chad', 'تشاد', null, null, null, null, null, null),
(43, 'Chile', 'شيلي', null, null, null, null, null, null),
(44, 'China', 'الصين', null, null, null, null, null, null),
(45, 'Christmas Island', 'جزيرة كريسماس', null, null, null, null, null, null),
(46, 'Cocos (Keeling) Islands', 'جزر كوكوس (كيلينغ)', null, null, null, null, null, null),
(47, 'Colombia', 'كولومبيا', null, null, null, null, null, null),
(48, 'Comoros', 'جزر القمر', null, null, null, null, null, null),
(49, 'Republic Of The Congo', 'جمهورية الكونغو', null, null, null, null, null, null),
(50, 'Democratic Republic Of The Congo', 'جمهورية الكونغو الديمقراطية', null, null, null, null, null, null),
(51, 'Cook Islands', 'جزر كوك', null, null, null, null, null, null),
(52, 'Costa Rica', 'كوستاريكا', null, null, null, null, null, null),
(53, 'Cote DIvoire (Ivory Coast)', 'ساحل العاج', null, null, null, null, null, null),
(54, 'Croatia (Hrvatska)', 'كرواتيا', null, null, null, null, null, null),
(55, 'Cuba', 'كوبا', null, null, null, null, null, null),
(56, 'Cyprus', 'قبرص', null, null, null, null, null, null),
(57, 'Czech Republic', 'الجمهورية التشيكية', null, null, null, null, null, null),
(58, 'Denmark', 'الدانمارك', null, null, null, null, null, null),
(59, 'Djibouti', 'جيبوتي', null, null, null, null, null, null),
(60, 'Dominica', 'دومينيكا', null, null, null, null, null, null),
(61, 'Dominican Republic', 'جمهورية الدومينيكان', null, null, null, null, null, null),
(62, 'East Timor', 'تيمور الشرقية', null, null, null, null, null, null),
(63, 'Ecuador', 'إكوادور', null, null, null, null, null, null),
(64, 'Egypt', 'مصر', null, null, null, null, null, null),
(65, 'El Salvador', 'السلفادور', null, null, null, null, null, null),
(66, 'Equatorial Guinea', 'غينيا الاستوائية', null, null, null, null, null, null),
(67, 'Eritrea', 'إريتريا', null, null, null, null, null, null),
(68, 'Estonia', 'إستونيا', null, null, null, null, null, null),
(69, 'Ethiopia', 'إثيوبيا', null, null, null, null, null, null),
(70, 'External Territories of Australia', 'الأراضي الخارجية لأستراليا', null, null, null, null, null, null),
(71, 'Falkland Islands', 'جزر فوكلاند', null, null, null, null, null, null),
(72, 'Faroe Islands', 'جزر فارو', null, null, null, null, null, null),
(73, 'Fiji Islands', 'جزر فيجي', null, null, null, null, null, null),
(74, 'Finland', 'فنلندا', null, null, null, null, null, null),
(75, 'France', 'فرنسا', null, null, null, null, null, null),
(76, 'French Guiana', 'غويانا الفرنسية', null, null, null, null, null, null),
(77, 'French Polynesia', 'بولينيزيا الفرنسية', null, null, null, null, null, null),
(78, 'French Southern Territories', 'الأقاليم الجنوبية لفرنسا', null, null, null, null, null, null),
(79, 'Gabon', 'الغابون', null, null, null, null, null, null),
(80, 'Gambia The', 'غامبيا', null, null, null, null, null, null),
(81, 'Georgia', 'جورجيا', null, null, null, null, null, null),
(82, 'Germany', 'ألمانيا', null, null, null, null, null, null),
(83, 'Ghana', 'غانا', null, null, null, null, null, null),
(84, 'Gibraltar', 'جبل طارق', null, null, null, null, null, null),
(85, 'Greece', 'اليونان', null, null, null, null, null, null),
(86, 'Greenland', 'جرينلاند', null, null, null, null, null, null),
(87, 'Grenada', 'جرينادا', null, null, null, null, null, null),
(88, 'Guadeloupe', 'جوادلوب', null, null, null, null, null, null),
(89, 'Guam', 'غوام', null, null, null, null, null, null),
(90, 'Guatemala', 'غواتيمالا', null, null, null, null, null, null),
(91, 'Guernsey and Alderney', 'غيرنسي وألدرني', null, null, null, null, null, null),
(92, 'Guinea', 'غينيا', null, null, null, null, null, null),
(93, 'Guinea-Bissau', 'غينيا بيساو', null, null, null, null, null, null),
(94, 'Guyana', 'غيانا', null, null, null, null, null, null),
(95, 'Haiti', 'هايتي', null, null, null, null, null, null),
(96, 'Heard and McDonald Islands', 'جزيرة هيرد وجزر ماكدونالد', null, null, null, null, null, null),
(97, 'Honduras', 'هندوراس', null, null, null, null, null, null),
(98, 'Hong Kong S.A.R.', 'هونج كونج', null, null, null, null, null, null),
(99, 'Hungary', 'هنغاريا', null, null, null, null, null, null),
(100, 'Iceland', 'آيسلندا', null, null, null, null, null, null),
(101, 'India', 'الهند', null, null, null, null, null, null),
(102, 'Indonesia', 'إندونيسيا', null, null, null, null, null, null),
(103, 'Iran', 'إيران', null, null, null, null, null, null),
(104, 'Iraq', 'العراق', null, null, null, null, null, null),
(105, 'Ireland', 'أيرلندا', null, null, null, null, null, null),
(107, 'Italy', 'إيطاليا', null, null, null, null, null, null),
(108, 'Jamaica', 'جامايكا', null, null, null, null, null, null),
(109, 'Japan', 'اليابان', null, null, null, null, null, null),
(110, 'Jersey', 'جيرزي', null, null, null, null, null, null),
(111, 'Jordan', 'الأردن', null, null, null, null, null, null),
(112, 'Kazakhstan', 'كازاخستان', null, null, null, null, null, null),
(113, 'Kenya', 'كينيا', null, null, null, null, null, null),
(114, 'Kiribati', 'كيريباتي', null, null, null, null, null, null),
(115, 'Korea North', 'كوريا الشمالية', null, null, null, null, null, null),
(116, 'Korea South', 'كوريا الجنوبية', null, null, null, null, null, null),
(117, 'Kuwait', 'الكويت', null, null, null, null, null, null),
(118, 'Kyrgyzstan', 'قيرغيزستان', null, null, null, null, null, null),
(119, 'Laos', 'لاوس', null, null, null, null, null, null),
(120, 'Latvia', 'لاتفيا', null, null, null, null, null, null),
(121, 'Lebanon', 'لبنان', null, null, null, null, null, null),
(122, 'Lesotho', 'ليسوتو', null, null, null, null, null, null),
(123, 'Liberia', 'ليبيريا', null, null, null, null, null, null),
(124, 'Libya', 'ليبيا', null, null, null, null, null, null),
(125, 'Liechtenstein', 'ليختنشتاين', null, null, null, null, null, null),
(126, 'Lithuania', 'ليتوانيا', null, null, null, null, null, null),
(127, 'Luxembourg', 'لوكسمبورج', null, null, null, null, null, null),
(128, 'Macau S.A.R.', 'ماكاو', null, null, null, null, null, null),
(129, 'Macedonia', 'مقدونيا', null, null, null, null, null, null),
(130, 'Madagascar', 'مدغشقر', null, null, null, null, null, null),
(131, 'Malawi', 'مالاوي', null, null, null, null, null, null),
(132, 'Malaysia', 'ماليزيا', null, null, null, null, null, null),
(133, 'Maldives', 'المالديف', null, null, null, null, null, null),
(134, 'Mali', 'مالي', null, null, null, null, null, null),
(135, 'Malta', 'مالطا', null, null, null, null, null, null),
(136, 'Man (Isle of)', 'جزيرة مان', null, null, null, null, null, null),
(137, 'Marshall Islands', 'جزر مارشال', null, null, null, null, null, null),
(138, 'Martinique', 'مارتينيك', null, null, null, null, null, null),
(139, 'Mauritania', 'موريتانيا', null, null, null, null, null, null),
(140, 'Mauritius', 'موريشيوس', null, null, null, null, null, null),
(141, 'Mayotte', 'مايوت', null, null, null, null, null, null),
(142, 'Mexico', 'المكسيك', null, null, null, null, null, null),
(143, 'Micronesia', 'ميكرونيزيا', null, null, null, null, null, null),
(144, 'Moldova', 'مولدوفا', null, null, null, null, null, null),
(145, 'Monaco', 'موناكو', null, null, null, null, null, null),
(146, 'Mongolia', 'منغوليا', null, null, null, null, null, null),
(147, 'Montserrat', 'مونتسيرات', null, null, null, null, null, null),
(148, 'Morocco', 'المغرب', null, null, null, null, null, null),
(149, 'Mozambique', 'موزمبيق', null, null, null, null, null, null),
(150, 'Myanmar', 'ميانمار', null, null, null, null, null, null),
(151, 'Namibia', 'ناميبيا', null, null, null, null, null, null),
(152, 'Nauru', 'ناورو', null, null, null, null, null, null),
(153, 'Nepal', 'نيبال', null, null, null, null, null, null),
(154, 'Netherlands Antilles', 'جزر الأنتيل الهولندية', null, null, null, null, null, null),
(155, 'Netherlands The', 'هولندا', null, null, null, null, null, null),
(156, 'New Caledonia', 'كاليدونيا الجديدة', null, null, null, null, null, null),
(157, 'New Zealand', 'نيوزيلندا', null, null, null, null, null, null),
(158, 'Nicaragua', 'نيكاراغوا', null, null, null, null, null, null),
(159, 'Niger', 'النيجر', null, null, null, null, null, null),
(160, 'Nigeria', 'نيجيريا', null, null, null, null, null, null),
(161, 'Niue', 'نيوي', null, null, null, null, null, null),
(162, 'Norfolk Island', 'جزيرة نورفولك', null, null, null, null, null, null),
(163, 'Northern Mariana Islands', 'جزر ماريانا الشمالية', null, null, null, null, null, null),
(164, 'Norway', 'النرويج', null, null, null, null, null, null),
(165, 'Oman', 'عمان', null, null, null, null, null, null),
(166, 'Pakistan', 'باكستان', null, null, null, null, null, null),
(167, 'Palau', 'بالاو', null, null, null, null, null, null),
(168, 'Palestinian Territory Occupied', 'الأراضي الفلسطينية المحتلة', null, null, null, null, null, null),
(169, 'Panama', 'بنما', null, null, null, null, null, null),
(170, 'Papua new Guinea', 'بابوا غينيا الجديدة', null, null, null, null, null, null),
(171, 'Paraguay', 'باراغواي', null, null, null, null, null, null),
(172, 'Peru', 'بيرو', null, null, null, null, null, null),
(173, 'Philippines', 'الفلبين', null, null, null, null, null, null),
(174, 'Pitcairn Island', 'جزيرة بيتكيرن', null, null, null, null, null, null),
(175, 'Poland', 'بولندا', null, null, null, null, null, null),
(176, 'Portugal', 'البرتغال', null, null, null, null, null, null),
(177, 'Puerto Rico', 'بورتوريكو', null, null, null, null, null, null),
(178, 'Qatar', 'قطر', null, null, null, null, null, null),
(179, 'Reunion', 'جمعية', null, null, null, null, null, null),
(180, 'Romania', 'رومانيا', null, null, null, null, null, null),
(181, 'Russia', 'روسيا', null, null, null, null, null, null),
(182, 'Rwanda', 'رواندا', null, null, null, null, null, null),
(183, 'Saint Helena', 'سانت هيلينا', null, null, null, null, null, null),
(184, 'Saint Kitts And Nevis', 'سانت كيتس ونيفيس', null, null, null, null, null, null),
(185, 'Saint Lucia', 'سانت لوسيا', null, null, null, null, null, null),
(186, 'Saint Pierre and Miquelon', 'سانت بيير وميكلون', null, null, null, null, null, null),
(187, 'Saint Vincent And The Grenadines', 'سانت فنسنت وجزر غرينادين', null, null, null, null, null, null),
(188, 'Samoa', 'ساموا', null, null, null, null, null, null),
(189, 'San Marino', 'سان مارينو', null, null, null, null, null, null),
(190, 'Sao Tome and Principe', 'ساو تومي وبرينسيبي', null, null, null, null, null, null),
(192, 'Senegal', 'السنغال', null, null, null, null, null, null),
(193, 'Serbia', 'صربيا', null, null, null, null, null, null),
(194, 'Seychelles', 'سيشل', null, null, null, null, null, null),
(195, 'Sierra Leone', 'سيراليون', null, null, null, null, null, null),
(196, 'Singapore', 'سنغافورة', null, null, null, null, null, null),
(197, 'Slovakia', 'سلوفاكيا', null, null, null, null, null, null),
(198, 'Slovenia', 'سلوفينيا', null, null, null, null, null, null),
(199, 'Smaller Territories of the UK', 'الأراضي الصغيرة للمملكة المتحدة', null, null, null, null, null, null),
(200, 'Solomon Islands', 'جزر سليمان', null, null, null, null, null, null),
(201, 'Somalia', 'الصومال', null, null, null, null, null, null),
(202, 'South Africa', 'جنوب أفريقيا', null, null, null, null, null, null),
(203, 'South Georgia', 'جورجيا الجنوبية', null, null, null, null, null, null),
(204, 'South Sudan', 'جنوب السودان', null, null, null, null, null, null),
(205, 'Spain', 'إسبانيا', null, null, null, null, null, null),
(206, 'Sri Lanka', 'سريلانكا', null, null, null, null, null, null),
(207, 'Sudan', 'السودان', null, null, null, null, null, null),
(208, 'Suriname', 'سورينام', null, null, null, null, null, null),
(209, 'Svalbard And Jan Mayen Islands', 'سفالبارد وجان ماين', null, null, null, null, null, null),
(210, 'Swaziland', 'سوازيلاند', null, null, null, null, null, null),
(211, 'Sweden', 'السويد', null, null, null, null, null, null),
(212, 'Switzerland', 'سويسرا', null, null, null, null, null, null),
(213, 'Syria', 'سوريا', null, null, null, null, null, null),
(214, 'Taiwan', 'تايوان', null, null, null, null, null, null),
(215, 'Tajikistan', 'طاجيكستان', null, null, null, null, null, null),
(216, 'Tanzania', 'تنزانيا', null, null, null, null, null, null),
(217, 'Thailand', 'تايلاند', null, null, null, null, null, null),
(218, 'Togo', 'توغو', null, null, null, null, null, null),
(219, 'Tokelau', 'توكيلاو', null, null, null, null, null, null),
(220, 'Tonga', 'تونغا', null, null, null, null, null, null),
(221, 'Trinidad And Tobago', 'ترينيداد وتوباغو', null, null, null, null, null, null),
(222, 'Tunisia', 'تونس', null, null, null, null, null, null),
(223, 'Turkey', 'تركيا', null, null, null, null, null, null),
(224, 'Turkmenistan', 'تركمانستان', null, null, null, null, null, null),
(225, 'Turks And Caicos Islands', 'جزر تركس وكايكوس', null, null, null, null, null, null),
(226, 'Tuvalu', 'توفالو', null, null, null, null, null, null),
(227, 'Uganda', 'أوغندا', null, null, null, null, null, null),
(228, 'Ukraine', 'أوكرانيا', null, null, null, null, null, null),
(229, 'United Arab Emirates', 'الإمارات العربية المتحدة', null, null, null, null, null, null),
(230, 'United Kingdom', 'المملكة المتحدة', null, null, null, null, null, null),
(231, 'United States', 'الولايات المتحدة', null, null, null, null, null, null),
(232, 'United States Minor Outlying Islands', 'جزر الولايات المتحدة الصغيرة النائية', null, null, null, null, null, null),
(233, 'Uruguay', 'أوروغواي', null, null, null, null, null, null),
(234, 'Uzbekistan', 'أوزبكستان', null, null, null, null, null, null),
(235, 'Vanuatu', 'فانواتو', null, null, null, null, null, null),
(236, 'Vatican City State (Holy See)', 'دولة الفاتيكان (الكرسي الرسولي)', null, null, null, null, null, null),
(237, 'Venezuela', 'فنزويلا', null, null, null, null, null, null),
(238, 'Vietnam', 'فيتنام', null, null, null, null, null, null),
(239, 'Virgin Islands (British)', 'جزر فيرجن (بريطاني)', null, null, null, null, null, null),
(240, 'Virgin Islands (US)', 'جزر فيرجن (الولايات المتحدة)', null, null, null, null, null, null),
(241, 'Wallis And Futuna Islands', 'جزر واليس وفوتونا', null, null, null, null, null, null),
(242, 'Western Sahara', 'الصحراء الغربية', null, null, null, null, null, null),
(243, 'Yemen', 'اليمن', null, null, null, null, null, null),
(244, 'Yugoslavia', 'يوغوسلافيا', null, null, null, null, null, null),
(245, 'Zambia', 'زامبيا', null, null, null, null, null, null),
(246, 'Zimbabwe', 'زيمبابوي', null, null, null, null, null, null),
(247, 'Palestine', 'فلسطين', null, null, null, null, null, null)");
    }
}
