<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class CountryCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('country_codes')->truncate();

        $array = [
            ['code' => '966', 'country_en' => 'Saudi Arabia (+966)', 'country_ar' => 'المملكة العربية السعودية (+966)'],
            ['code' => '44', 'country_en' => 'UK (+44)', 'country_ar' => 'المملكة المتحدة (+44)'],
            ['code' => '1', 'country_en' => 'USA (+1)', 'country_ar' => 'الولايات المتحدة الأمريكية (+1)'],
            ['code' => '213', 'country_en' => 'Algeria (+213)', 'country_ar' => 'الجزائر (+213)'],
            ['code' => '376', 'country_en' => 'Andorra (+376)', 'country_ar' => 'أندورا (+376)'],
            ['code' => '244', 'country_en' => 'Angola (+244)', 'country_ar' => 'أنغولا (+244)'],
            ['code' => '1264', 'country_en' => 'Anguilla (+1264)', 'country_ar' => 'أنغويلا (+1264)'],
            ['code' => '1268', 'country_en' => 'Antigua & Barbuda (+1268)', 'country_ar' => 'أنتيغوا وبربودا (+1268)'],
            ['code' => '54', 'country_en' => 'Argentina (+54)', 'country_ar' => 'الأرجنتين (+54)'],
            ['code' => '374', 'country_en' => 'Armenia (+374)', 'country_ar' => 'أرمينيا (+374)'],
            ['code' => '297', 'country_en' => 'Aruba (+297)', 'country_ar' => 'أروبا (+297)'],
            ['code' => '61', 'country_en' => 'Australia (+61)', 'country_ar' => 'أستراليا (+61)'],
            ['code' => '43', 'country_en' => 'Austria (+43)', 'country_ar' => 'النمسا (+43)'],
            ['code' => '994', 'country_en' => 'Azerbaijan (+994)', 'country_ar' => 'أذربيجان (+994)'],
            ['code' => '1242', 'country_en' => 'Bahamas (+1242)', 'country_ar' => 'البهاما (+1242)'],
            ['code' => '973', 'country_en' => 'Bahrain (+973)', 'country_ar' => 'البحرين (+973)'],
            ['code' => '880', 'country_en' => 'Bangladesh (+880)', 'country_ar' => 'بنغلاديش (+880)'],
            ['code' => '1246', 'country_en' => 'Barbados (+1246)', 'country_ar' => 'بربادوس (+1246)'],
            ['code' => '375', 'country_en' => 'Belarus (+375)', 'country_ar' => 'بيلاروسيا (+375)'],
            ['code' => '32', 'country_en' => 'Belgium (+32)', 'country_ar' => 'بلجيكا (+32)'],
            ['code' => '501', 'country_en' => 'Belize (+501)', 'country_ar' => 'بليز (+501)'],
            ['code' => '229', 'country_en' => 'Benin (+229)', 'country_ar' => 'بنين (+229)'],
            ['code' => '1441', 'country_en' => 'Bermuda (+1441)', 'country_ar' => 'برمودا (+1441)'],
            ['code' => '975', 'country_en' => 'Bhutan (+975)', 'country_ar' => 'بوتان (+975)'],
            ['code' => '591', 'country_en' => 'Bolivia (+591)', 'country_ar' => 'بوليفيا (+591)'],
            ['code' => '387', 'country_en' => 'Bosnia Herzegovina (+387)', 'country_ar' => 'البوسنة والهرسك (+387)'],
            ['code' => '267', 'country_en' => 'Botswana (+267)', 'country_ar' => 'بوتسوانا (+267)'],
            ['code' => '55', 'country_en' => 'Brazil (+55)', 'country_ar' => 'البرازيل (+55)'],
            ['code' => '673', 'country_en' => 'Brunei (+673)', 'country_ar' => 'بروناي (+673)'],
            ['code' => '359', 'country_en' => 'Bulgaria (+359)', 'country_ar' => 'بلغاريا (+359)'],
            ['code' => '226', 'country_en' => 'Burkina Faso (+226)', 'country_ar' => 'بوركينا فاسو (+226)'],
            ['code' => '257', 'country_en' => 'Burundi (+257)', 'country_ar' => 'بوروندي (+257)'],
            ['code' => '855', 'country_en' => 'Cambodia (+855)', 'country_ar' => 'كمبوديا (+855)'],
            ['code' => '237', 'country_en' => 'Cameroon (+237)', 'country_ar' => 'الكاميرون (+237)'],
            ['code' => '1', 'country_en' => 'Canada (+1)', 'country_ar' => 'كندا (+1)'],
            ['code' => '238', 'country_en' => 'Cape Verde Islands (+238)', 'country_ar' => 'الرأس الأخضر (+238)'],
            ['code' => '1345', 'country_en' => 'Cayman Islands (+1345)', 'country_ar' => 'جزر كايمان (+1345)'],
            ['code' => '236', 'country_en' => 'Central African Republic (+236)', 'country_ar' => 'جمهورية أفريقيا الوسطى (+236)'],
            ['code' => '56', 'country_en' => 'Chile (+56)', 'country_ar' => 'تشيلي (+56)'],
            ['code' => '86', 'country_en' => 'China (+86)', 'country_ar' => 'الصين (+86)'],
            ['code' => '57', 'country_en' => 'Colombia (+57)', 'country_ar' => 'كولومبيا (+57)'],
            ['code' => '269', 'country_en' => 'Comoros (+269)', 'country_ar' => 'جزر القمر (+269)'],
            ['code' => '242', 'country_en' => 'Congo (+242)', 'country_ar' => 'الكونغو (+242)'],
            ['code' => '682', 'country_en' => 'Cook Islands (+682)', 'country_ar' => 'جزر كوك (+682)'],
            ['code' => '506', 'country_en' => 'Costa Rica (+506)', 'country_ar' => 'كوستاريكا (+506)'],
            ['code' => '385', 'country_en' => 'Croatia (+385)', 'country_ar' => 'كرواتيا (+385)'],
            ['code' => '53', 'country_en' => 'Cuba (+53)', 'country_ar' => 'كوبا (+53)'],
            ['code' => '90392', 'country_en' => 'Cyprus North (+90392)', 'country_ar' => 'قبرص الشمالية (+90392)'],
            ['code' => '357', 'country_en' => 'Cyprus South (+357)', 'country_ar' => 'قبرص الجنوبية (+357)'],
            ['code' => '42', 'country_en' => 'Czech Republic (+42)', 'country_ar' => 'جمهورية التشيك (+42)'],
            ['code' => '45', 'country_en' => 'Denmark (+45)', 'country_ar' => 'الدانمارك (+45)'],
            ['code' => '253', 'country_en' => 'Djibouti (+253)', 'country_ar' => 'جيبوتي (+253)'],
            ['code' => '1809', 'country_en' => 'Dominica (+1809)', 'country_ar' => 'دومينيكا (+1809)'],
            ['code' => '1809', 'country_en' => 'Dominican Republic (+1809)', 'country_ar' => 'جمهورية الدومينيكان (+1809)'],
            ['code' => '593', 'country_en' => 'Ecuador (+593)', 'country_ar' => 'الإكوادور (+593)'],
            ['code' => '20', 'country_en' => 'Egypt (+20)', 'country_ar' => 'مصر (+20)'],
            ['code' => '503', 'country_en' => 'El Salvador (+503)', 'country_ar' => 'السلفادور (+503)'],
            ['code' => '240', 'country_en' => 'Equatorial Guinea (+240)', 'country_ar' => 'غينيا الاستوائية (+240)'],
            ['code' => '291', 'country_en' => 'Eritrea (+291)', 'country_ar' => 'إريتريا (+291)'],
            ['code' => '372', 'country_en' => 'Estonia (+372)', 'country_ar' => 'إستونيا (+372)'],
            ['code' => '251', 'country_en' => 'Ethiopia (+251)', 'country_ar' => 'أثيوبيا (+251)'],
            ['code' => '500', 'country_en' => 'Falkland Islands (+500)', 'country_ar' => 'جزر فوكلاند (+500)'],
            ['code' => '298', 'country_en' => 'Faroe Islands (+298)', 'country_ar' => 'جزر فارو (+298)'],
            ['code' => '679', 'country_en' => 'Fiji (+679)', 'country_ar' => 'فيجي (+679)'],
            ['code' => '358', 'country_en' => 'Finland (+358)', 'country_ar' => 'فنلندا (+358)'],
            ['code' => '33', 'country_en' => 'France (+33)', 'country_ar' => 'فرنسا (+33)'],
            ['code' => '594', 'country_en' => 'French Guiana (+594)', 'country_ar' => 'غويانا الفرنسية (+594)'],
            ['code' => '689', 'country_en' => 'French Polynesia (+689)', 'country_ar' => 'بولينيزيا الفرنسية (+689)'],
            ['code' => '241', 'country_en' => 'Gabon (+241)', 'country_ar' => 'الغابون (+241)'],
            ['code' => '220', 'country_en' => 'Gambia (+220)', 'country_ar' => 'غامبيا (+220)'],
            ['code' => '7880', 'country_en' => 'Georgia (+7880)', 'country_ar' => 'جورجيا (+7880)'],
            ['code' => '49', 'country_en' => 'Germany (+49)', 'country_ar' => 'ألمانيا (+49)'],
            ['code' => '233', 'country_en' => 'Ghana (+233)', 'country_ar' => 'غانا (+233)'],
            ['code' => '350', 'country_en' => 'Gibraltar (+350)', 'country_ar' => 'جبل طارق (+350)'],
            ['code' => '30', 'country_en' => 'Greece (+30)', 'country_ar' => 'اليونان (+30)'],
            ['code' => '299', 'country_en' => 'Greenland (+299)', 'country_ar' => 'جرينلاند (+299)'],
            ['code' => '1473', 'country_en' => 'Grenada (+1473)', 'country_ar' => 'غرينادا (+1473)'],
            ['code' => '590', 'country_en' => 'Guadeloupe (+590)', 'country_ar' => 'غوادلوب (+590)'],
            ['code' => '671', 'country_en' => 'Guam (+671)', 'country_ar' => 'غوام (+671)'],
            ['code' => '502', 'country_en' => 'Guatemala (+502)', 'country_ar' => 'غواتيمالا (+502)'],
            ['code' => '224', 'country_en' => 'Guinea (+224)', 'country_ar' => 'غينيا (+224)'],
            ['code' => '245', 'country_en' => 'Guinea - Bissau (+245)', 'country_ar' => 'غينيا - بيساو (+245)'],
            ['code' => '592', 'country_en' => 'Guyana (+592)', 'country_ar' => 'غيانا (+592)'],
            ['code' => '509', 'country_en' => 'Haiti (+509)', 'country_ar' => 'هايتي (+509)'],
            ['code' => '504', 'country_en' => 'Honduras (+504)', 'country_ar' => 'هندوراس (+504)'],
            ['code' => '852', 'country_en' => 'Hong Kong (+852)', 'country_ar' => 'هونغ كونغ (+852)'],
            ['code' => '36', 'country_en' => 'Hungary (+36)', 'country_ar' => 'هنغاريا (+36)'],
            ['code' => '354', 'country_en' => 'Iceland (+354)', 'country_ar' => 'أيسلندا (+354)'],
            ['code' => '91', 'country_en' => 'India (+91)', 'country_ar' => 'الهند (+91)'],
            ['code' => '62', 'country_en' => 'Indonesia (+62)', 'country_ar' => 'أندونيسيا (+62)'],
            ['code' => '98', 'country_en' => 'Iran (+98)', 'country_ar' => 'إيران (+98)'],
            ['code' => '964', 'country_en' => 'Iraq (+964)', 'country_ar' => 'العراق (+964)'],
            ['code' => '353', 'country_en' => 'Ireland (+353)', 'country_ar' => 'أيرلندا (+353)'],
            ['code' => '972', 'country_en' => 'Israel (+972)', 'country_ar' => 'إسرائيل (+972)'],
            ['code' => '39', 'country_en' => 'Italy (+39)', 'country_ar' => 'إيطاليا (+39)'],
            ['code' => '1876', 'country_en' => 'Jamaica (+1876)', 'country_ar' => 'جامايكا (+1876)'],
            ['code' => '81', 'country_en' => 'Japan (+81)', 'country_ar' => 'اليابان (+81)'],
            ['code' => '962', 'country_en' => 'Jordan (+962)', 'country_ar' => 'الأردن (+962)'],
            ['code' => '7', 'country_en' => 'Kazakhstan (+7)', 'country_ar' => 'كازاخستان (+7)'],
            ['code' => '254', 'country_en' => 'Kenya (+254)', 'country_ar' => 'كينيا (+254)'],
            ['code' => '686', 'country_en' => 'Kiribati (+686)', 'country_ar' => 'كيريباتي (+686)'],
            ['code' => '850', 'country_en' => 'Korea North (+850)', 'country_ar' => 'كوريا الشمالية (+850)'],
            ['code' => '82', 'country_en' => 'Korea South (+82)', 'country_ar' => 'كوريا الجنوبية (+82)'],
            ['code' => '965', 'country_en' => 'Kuwait (+965)', 'country_ar' => 'الكويت (+965)'],
            ['code' => '996', 'country_en' => 'Kyrgyzstan (+996)', 'country_ar' => 'قرغيزستان (+996)'],
            ['code' => '856', 'country_en' => 'Laos (+856)', 'country_ar' => 'لاوس (+856)'],
            ['code' => '371', 'country_en' => 'Latvia (+371)', 'country_ar' => 'لاتفيا (+371)'],
            ['code' => '961', 'country_en' => 'Lebanon (+961)', 'country_ar' => 'لبنان (+961)'],
            ['code' => '266', 'country_en' => 'Lesotho (+266)', 'country_ar' => 'ليسوتو (+266)'],
            ['code' => '231', 'country_en' => 'Liberia (+231)', 'country_ar' => 'ليبيريا (+231)'],
            ['code' => '218', 'country_en' => 'Libya (+218)', 'country_ar' => 'ليبيا (+218)'],
            ['code' => '417', 'country_en' => 'Liechtenstein (+417)', 'country_ar' => 'ليختنشتاين (+417)'],
            ['code' => '370', 'country_en' => 'Lithuania (+370)', 'country_ar' => 'ليتوانيا (+370)'],
            ['code' => '352', 'country_en' => 'Luxembourg (+352)', 'country_ar' => 'لوكسمبورغ (+352)'],
            ['code' => '853', 'country_en' => 'Macao (+853)', 'country_ar' => 'ماكاو (+853)'],
            ['code' => '389', 'country_en' => 'Macedonia (+389)', 'country_ar' => 'مقدونيا (+389)'],
            ['code' => '261', 'country_en' => 'Madagascar (+261)', 'country_ar' => 'مدغشقر (+261)'],
            ['code' => '265', 'country_en' => 'Malawi (+265)', 'country_ar' => 'مالاوي (+265)'],
            ['code' => '60', 'country_en' => 'Malaysia (+60)', 'country_ar' => 'ماليزيا (+60)'],
            ['code' => '960', 'country_en' => 'Maldives (+960)', 'country_ar' => 'جزر المالديف (+960)'],
            ['code' => '223', 'country_en' => 'Mali (+223)', 'country_ar' => 'مالي (+223)'],
            ['code' => '356', 'country_en' => 'Malta (+356)', 'country_ar' => 'مالطا (+356)'],
            ['code' => '692', 'country_en' => 'Marshall Islands (+692)', 'country_ar' => 'جزر مارشال (+692)'],
            ['code' => '596', 'country_en' => 'Martinique (+596)', 'country_ar' => 'مارتينيك (+596)'],
            ['code' => '222', 'country_en' => 'Mauritania (+222)', 'country_ar' => 'موريتانيا (+222)'],
            ['code' => '269', 'country_en' => 'Mayotte (+269)', 'country_ar' => 'مايوت (+269)'],
            ['code' => '52', 'country_en' => 'Mexico (+52)', 'country_ar' => 'المكسيك (+52)'],
            ['code' => '691', 'country_en' => 'Micronesia (+691)', 'country_ar' => 'ميكرونيزيا (+691)'],
            ['code' => '373', 'country_en' => 'Moldova (+373)', 'country_ar' => 'مولدوفا (+373)'],
            ['code' => '377', 'country_en' => 'Monaco (+377)', 'country_ar' => 'موناكو (+377)'],
            ['code' => '976', 'country_en' => 'Mongolia (+976)', 'country_ar' => 'منغوليا (+976)'],
            ['code' => '1664', 'country_en' => 'Montserrat (+1664)', 'country_ar' => 'مونتسيرات (+1664)'],
            ['code' => '212', 'country_en' => 'Morocco (+212)', 'country_ar' => 'المغرب (+212)'],
            ['code' => '258', 'country_en' => 'Mozambique (+258)', 'country_ar' => 'موزمبيق (+258)'],
            ['code' => '95', 'country_en' => 'Myanmar (+95)', 'country_ar' => 'ميانمار (+95)'],
            ['code' => '264', 'country_en' => 'Namibia (+264)', 'country_ar' => 'ناميبيا (+264)'],
            ['code' => '674', 'country_en' => 'Nauru (+674)', 'country_ar' => 'ناورو (+674)'],
            ['code' => '977', 'country_en' => 'Nepal (+977)', 'country_ar' => 'نيبال (+977)'],
            ['code' => '31', 'country_en' => 'Netherlands (+31)', 'country_ar' => 'هولندا (+31)'],
            ['code' => '687', 'country_en' => 'New Caledonia (+687)', 'country_ar' => 'كاليدونيا الجديدة (+687)'],
            ['code' => '64', 'country_en' => 'New Zealand (+64)', 'country_ar' => 'نيوزيلندا (+64)'],
            ['code' => '505', 'country_en' => 'Nicaragua (+505)', 'country_ar' => 'نيكاراجوا (+505)'],
            ['code' => '227', 'country_en' => 'Niger (+227)', 'country_ar' => 'النيجر (+227)'],
            ['code' => '234', 'country_en' => 'Nigeria (+234)', 'country_ar' => 'نيجيريا (+234)'],
            ['code' => '683', 'country_en' => 'Niue (+683)', 'country_ar' => 'نيوي (+683)'],
            ['code' => '672', 'country_en' => 'Norfolk Islands (+672)', 'country_ar' => 'جزر نورفولك (+672)'],
            ['code' => '670', 'country_en' => 'Northern Marianas (+670)', 'country_ar' => 'جزر ماريانا الشمالية (+670)'],
            ['code' => '47', 'country_en' => 'Norway (+47)', 'country_ar' => 'النرويج (+47)'],
            ['code' => '968', 'country_en' => 'Oman (+968)', 'country_ar' => 'عُمان (+968)'],
            ['code' => '680', 'country_en' => 'Palau (+680)', 'country_ar' => 'بالاو (+680)'],
            ['code' => '507', 'country_en' => 'Panama (+507)', 'country_ar' => 'بنما (+507)'],
            ['code' => '675', 'country_en' => 'Papua New Guinea (+675)', 'country_ar' => 'بابوا غينيا الجديدة (+675)'],
            ['code' => '595', 'country_en' => 'Paraguay (+595)', 'country_ar' => 'باراغواي (+595)'],
            ['code' => '51', 'country_en' => 'Peru (+51)', 'country_ar' => 'بيرو (+51)'],
            ['code' => '63', 'country_en' => 'Philippines (+63)', 'country_ar' => 'الفلبين (+63)'],
            ['code' => '48', 'country_en' => 'Poland (+48)', 'country_ar' => 'بولندا (+48)'],
            ['code' => '351', 'country_en' => 'Portugal (+351)', 'country_ar' => 'البرتغال (+351)'],
            ['code' => '1787', 'country_en' => 'Puerto Rico (+1787)', 'country_ar' => 'بورتوريكو (+1787)'],
            ['code' => '974', 'country_en' => 'Qatar (+974)', 'country_ar' => 'قطر (+974)'],
            ['code' => '262', 'country_en' => 'Reunion (+262)', 'country_ar' => 'روينيون (+262)'],
            ['code' => '40', 'country_en' => 'Romania (+40)', 'country_ar' => 'رومانيا (+40)'],
            ['code' => '7', 'country_en' => 'Russia (+7)', 'country_ar' => 'روسيا (+7)'],
            ['code' => '250', 'country_en' => 'Rwanda (+250)', 'country_ar' => 'رواندا (+250)'],
            ['code' => '378', 'country_en' => 'San Marino (+378)', 'country_ar' => 'سان مارينو (+378)'],
            ['code' => '239', 'country_en' => 'Sao Tome & Principe (+239)', 'country_ar' => 'ساو تومي وبرينسيبي (+239)'],
            ['code' => '966', 'country_en' => 'Saudi Arabia (+966)', 'country_ar' => 'المملكة العربية السعودية (+966)'],
            ['code' => '221', 'country_en' => 'Senegal (+221)', 'country_ar' => 'السنغال (+221)'],
            ['code' => '381', 'country_en' => 'Serbia (+381)', 'country_ar' => 'صربيا (+381)'],
            ['code' => '248', 'country_en' => 'Seychelles (+248)', 'country_ar' => 'سيشل (+248)'],
            ['code' => '232', 'country_en' => 'Sierra Leone (+232)', 'country_ar' => 'سيراليون (+232)'],
            ['code' => '65', 'country_en' => 'Singapore (+65)', 'country_ar' => 'سنغافورة (+65)'],
            ['code' => '421', 'country_en' => 'Slovak Republic (+421)', 'country_ar' => 'سلوفاكيا (+421)'],
            ['code' => '386', 'country_en' => 'Slovenia (+386)', 'country_ar' => 'سلوفينيا (+386)'],
            ['code' => '677', 'country_en' => 'Solomon Islands (+677)', 'country_ar' => 'جزر سليمان (+677)'],
            ['code' => '252', 'country_en' => 'Somalia (+252)', 'country_ar' => 'الصومال (+252)'],
            ['code' => '27', 'country_en' => 'South Africa (+27)', 'country_ar' => 'جنوب أفريقيا (+27)'],
            ['code' => '34', 'country_en' => 'Spain (+34)', 'country_ar' => 'إسبانيا (+34)'],
            ['code' => '94', 'country_en' => 'Sri Lanka (+94)', 'country_ar' => 'سريلانكا (+94)'],
            ['code' => '290', 'country_en' => 'St. Helena (+290)', 'country_ar' => 'سانت هيلينا (+290)'],
            ['code' => '1869', 'country_en' => 'St. Kitts (+1869)', 'country_ar' => 'سانت كيتس (+1869)'],
            ['code' => '1758', 'country_en' => 'St. Lucia (+1758)', 'country_ar' => 'سانت لوسيا (+1758)'],
            ['code' => '249', 'country_en' => 'Sudan (+249)', 'country_ar' => 'السودان (+249)'],
            ['code' => '597', 'country_en' => 'Suriname (+597)', 'country_ar' => 'سورينام (+597)'],
            ['code' => '268', 'country_en' => 'Swaziland (+268)', 'country_ar' => 'سوازيلاند (+268)'],
            ['code' => '46', 'country_en' => 'Sweden (+46)', 'country_ar' => 'السويد (+46)'],
            ['code' => '41', 'country_en' => 'Switzerland (+41)', 'country_ar' => 'سويسرا (+41)'],
            ['code' => '963', 'country_en' => 'Syria (+963)', 'country_ar' => 'سوريا (+963)'],
            ['code' => '886', 'country_en' => 'Taiwan (+886)', 'country_ar' => 'تايوان (+886)'],
            ['code' => '7', 'country_en' => 'Tajikstan (+7)', 'country_ar' => 'طاجيكستان (+7)'],
            ['code' => '66', 'country_en' => 'Thailand (+66)', 'country_ar' => 'تايلاند (+66)'],
            ['code' => '228', 'country_en' => 'Togo (+228)', 'country_ar' => 'توغو (+228)'],
            ['code' => '676', 'country_en' => 'Tonga (+676)', 'country_ar' => 'تونغا (+676)'],
            ['code' => '1868', 'country_en' => 'Trinidad & Tobago (+1868)', 'country_ar' => 'ترينيداد وتوباغو (+1868)'],
            ['code' => '216', 'country_en' => 'Tunisia (+216)', 'country_ar' => 'تونس (+216)'],
            ['code' => '90', 'country_en' => 'Turkey (+90)', 'country_ar' => 'تركيا (+90)'],
            ['code' => '7', 'country_en' => 'Turkmenistan (+7)', 'country_ar' => 'تركمانستان (+7)'],
            ['code' => '993', 'country_en' => 'Turkmenistan (+993)', 'country_ar' => 'تركمانستان (+993)'],
            ['code' => '1649', 'country_en' => 'Turks & Caicos Islands (+1649)', 'country_ar' => 'جزر تركس وكايكوس (+1649)'],
            ['code' => '688', 'country_en' => 'Tuvalu (+688)', 'country_ar' => 'توفالو (+688)'],
            ['code' => '256', 'country_en' => 'Uganda (+256)', 'country_ar' => 'أوغندا (+256)'],
            ['code' => '380', 'country_en' => 'Ukraine (+380)', 'country_ar' => 'أوكرانيا (+380)'],
            ['code' => '971', 'country_en' => 'United Arab Emirates (+971)', 'country_ar' => 'الإمارات العربية المتحدة (+971)'],
            ['code' => '598', 'country_en' => 'Uruguay (+598)', 'country_ar' => 'أوروغواي (+598)'],
            ['code' => '7', 'country_en' => 'Uzbekistan (+7)', 'country_ar' => 'أوزبكستان (+7)'],
            ['code' => '678', 'country_en' => 'Vanuatu (+678)', 'country_ar' => 'فانواتو (+678)'],
            ['code' => '379', 'country_en' => 'Vatican City (+379)', 'country_ar' => 'الفاتيكان (+379)'],
            ['code' => '58', 'country_en' => 'Venezuela (+58)', 'country_ar' => 'فنزويلا (+58)'],
            ['code' => '84', 'country_en' => 'Vietnam (+84)', 'country_ar' => 'فيتنام (+84)'],
            ['code' => '1284', 'country_en' => 'Virgin Islands - British (+1284)', 'country_ar' => 'جزر فيرجن - بريطانيا (+1284)'],
            ['code' => '1340', 'country_en' => 'Virgin Islands - US (+1340)', 'country_ar' => 'جزر فيرجن - الولايات المتحدة (+1340)'],
            ['code' => '681', 'country_en' => 'Wallis & Futuna (+681)', 'country_ar' => 'واليس وفوتونا (+681)'],
            ['code' => '969', 'country_en' => 'Yemen (North)(+969)', 'country_ar' => 'اليمن (الشمالية)(+969)'],
            ['code' => '967', 'country_en' => 'Yemen (South)(+967)', 'country_ar' => 'اليمن (الجنوبية)(+967)'],
            ['code' => '260', 'country_en' => 'Zambia (+260)', 'country_ar' => 'زامبيا (+260)'],
            ['code' => '263', 'country_en' => 'Zimbabwe (+263)', 'country_ar' => 'زيمبابوي (+263)'],
        ];


        $countryPhoneCodes = [];
        foreach ($array as $a) {
            $countryPhoneCodes[] = ['name_en' => $a['country_en'], 'name_ar' => $a['country_ar'], 'code' => $a['code']];
        }




        // Insert the country phone codes into the 'countries' table
        DB::table('country_codes')->insert($countryPhoneCodes);
    }
}
